name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    uses: pww217/k3s-home/.github/workflows/ci.yaml@main
    permissions:
      contents: read
      packages: write
    secrets: inherit
